### ISSUE TITLE
Remove sign up extra space in password form

### ISSUE THREAD

**Issue by mmmsss211** [mmmsss211/Incognito-Confessions#83]
![image](https://user-images.githubusercontent.com/6498007/235279649-ca35ae60-e867-41e7-b2a0-2836845f00f4.png)
remove extra space on the right of password

**Comment by yskooo** [comment]
from `space-x-6 `to `space-x-1 `
![image](https://user-images.githubusercontent.com/90546802/235309504-262e09c1-33a4-4f60-99ba-08c6bc18f658.png)

**Comment by yskooo** [comment]
`space-x-1`
![image](https://user-images.githubusercontent.com/90546802/235313982-18ff96c2-aab1-41e8-922d-5a762205d13c.png)
