### ISSUE TITLE
Enable heart react on confessions archive

### ISSUE THREAD

**Issue by mmmsss211** [mmmsss211/Incognito-Confessions#85]
![image](https://user-images.githubusercontent.com/6498007/235280000-c1e50ddb-b26a-4e39-bace-97e4713dd4e4.png)

Currently clicking on the heart button only redirect to the single confession view before they can be allowed to heart.
Remove the extra steps to heart by allowing to directly heart on archive page.

**Comment by IshmaelCasky** [comment]
![image](https://user-images.githubusercontent.com/40536128/235313576-56a3f896-e543-417f-b443-a294792225ee.png)

Added
